version: "3.7"
services:
  # go-app:
  #   build:
  #     context: .
  #     dockerfile: dockerfile
  #   container_name: go-app
  #   depends_on:
  #     - mongo
  #   environment:
  #     - PORT=8080
  #   ports:
  #     - "8080:8080"
  # mongo:
  #   image: "mongo:latest"
  #   container_name: mongo
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=admin
  #   ports:
  #     - "27017:27017"
  #   restart: always
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
